FROM node:12-alpine AS builder

ARG API_URL
ARG TILE_URL

RUN apk add --no-cache git curl bash

COPY package.json /client/package.json
COPY package-lock.json /client/package-lock.json

WORKDIR /client

RUN npm ci

COPY . /client

RUN npm run build

FROM nginx:1.17-alpine

COPY --from=builder /client/dist/ /usr/share/nginx/html/

CMD nginx -g 'daemon off;'
